name: generate contribution graph

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate contribution grid svg
        uses: Platane/snk@v3
        with:
          github_user_name: oktajianto
          outputs: |
            dist/github-contribution-grid.svg?palette=github-light
            dist/github-contribution-grid-dark.svg?palette=github-dark

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
